---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: check existence of ssh key
      command: test -e {{ private_key_path }}
      register: has_sshkey
      ignore_errors: True
    - name: create ssh key
      shell: "ssh-keygen -t rsa -N '' -f {{ private_key_path }}"
      when: has_sshkey.rc != 0
